spring:
  config:
    activate:
      on-profile: "local"
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:${DB_DATABASE_NAME}
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate: # hibernate 사용 설정
      ddl-auto: create-drop
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        show-sql: true
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: debug
h2:
  console:
    enabled: true