spring:
  profiles:
    active:
      - dev
  output:
    ansi:
      enabled: ALWAYS
  logging:
    level:
      org.hibernate.SQL: debug
h2:
  console:
    enabled: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 1800000 # 30 min
      refresh-token:
        expiration: 604800000 # 7 days